name: Tests

on:
  - push
  - pull_request

env:
  GO_VERSION: '1.16'

jobs:
  misspell-check:
    runs-on: ubuntu-latest
    container: pouchcontainer/pouchlinter:v0.1.2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint markdown files
        run: find  ./ -name  "*.md" | xargs mdl -r ~MD010,~MD013,~MD022,~MD024,~MD029,~MD031,~MD032,~MD033,~MD034,~MD036

  golang-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run client-helm unit test
        run: go test -v ./...

      - name: Run go fmt test
        run: hack/verify-gofmt.sh
        env:
          GO111MODULE: auto
